model:
  path: "hunyuanvideo-community/HunyuanVideo-I2V"
  dtype: "bfloat16"
  flow_shift: 7.0  #7.0 if i2v_stable else 17.0
  flow_reverse: false

generation:
  num_frames: 129
  num_inference_steps: 50
  guidance_scale: 6.0
  i2v_stable: true
  true_cfg_scale: 1.0

alg:
  use_low_pass_guidance: True

video:
  resolution: 360p
  fps: 30