model:
  path: "hunyuanvideo-community/HunyuanVideo-I2V"
  dtype: "bfloat16"
  flow_shift: 7.0  #7.0 if i2v_stable else 17.0
  flow_reverse: false

generation:
  num_frames: 129
  num_inference_steps: 50
  guidance_scale: 6.0
  i2v_stable: true
  true_cfg_scale: 1.0

alg:
  use_low_pass_guidance: True

  lp_filter_type: "down_up"
  lp_filter_in_latent: True

  lp_blur_sigma: null
  lp_blur_kernel_size: null
  lp_resize_factor: 0.625

  lp_strength_schedule_type: "interval"
  schedule_blur_kernel_size: False

  schedule_interval_start_time: 0.0
  schedule_interval_end_time: 0.04

  schedule_linear_start_weight: null
  schedule_linear_end_weight: null
  schedule_linear_end_time: null

video:
  resolution: 360p
  fps: 30